# Generated by Django 4.2.6 on 2024-02-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_decoritems_kitchenappliances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoritems',
            old_name='profile',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='kitchenappliances',
            old_name='profile',
            new_name='image',
        ),
    ]
