# Generated by Django 4.2.6 on 2024-02-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='deid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.decoritems'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='kitid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchenappliances'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registration_user'),
        ),
    ]
