# Generated by Django 4.2.6 on 2024-02-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_feedback_deid_feedback_kitid_feedback_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(null=True)),
                ('current_date', models.DateTimeField(null=True)),
                ('deid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.decoritems')),
                ('kitid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchenappliances')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registration_user')),
            ],
        ),
    ]
