# Generated by Django 4.2.6 on 2024-02-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='deid',
        ),
        migrations.RemoveField(
            model_name='request',
            name='kitid',
        ),
    ]
