# Generated by Django 4.2.6 on 2024-02-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='progress',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
