# Generated by Django 4.2.6 on 2024-02-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_request_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='deid',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='kitid',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.request'),
        ),
    ]
