# Generated by Django 4.2.6 on 2024-02-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('current_date', models.DateField(null=True)),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
            ],
        ),
    ]
