# Generated by Django 4.2.6 on 2024-02-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Successful', max_length=40, null=True),
        ),
    ]
