# Generated by Django 4.2.6 on 2024-02-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.decoritems'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kitid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchenappliances'),
        ),
        migrations.AddField(
            model_name='payment',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registration_user'),
        ),
    ]
