# Generated by Django 4.2.6 on 2024-02-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_payment_deid_payment_kitid_payment_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='kitid',
        ),
    ]
